[package]
version = "0.1.0"
name = "sp1-fuelstreamx-script"
edition = "2021"

[[bin]]
name = "genesis"
path = "bin/genesis.rs"

[[bin]]
name = "operator"
path = "bin/operator.rs"

[[bin]]
name = "vkey"
path = "bin/vkey.rs"

[dependencies]
primitives = { path = "../primitives" }

alloy = { version = "0.7.0", default-features = true, features = ["full"] }
tendermint = { workspace = true }
tendermint-light-client = { workspace = true }
tendermint-light-client-verifier = { workspace = true, features = ["rust-crypto"] }
tendermint-rpc = { workspace = true }
sp1-sdk = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
dotenv = { workspace = true }
subtle-encoding = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true }
hex = { workspace = true }
futures = { workspace = true }
env_logger = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }

fuel-sequencer-proto="0.1.0"
tonic = { version = "0.11", features = ["tls", "tls-roots"] }
unicode-ident = "1.0"

[build-dependencies]
sp1-build = "4.0.1"

[dev-dependencies]
wiremock = "0.6.2"
async-trait = "0.1.85"
tokio-stream = { version = "0.1.14",  features = ["net"]  }