[package]
version = "0.1.0"
name = "sp1-fuelstreamx-program"
edition = "2021"

[dependencies]
sp1-fuelstreamx-primitives = { workspace = true }

sp1-zkvm = { workspace = true }
tendermint-light-client-verifier = { workspace = true, default-features = true, features = ["rust-crypto"] }
tendermint = { workspace = true, default-features = true }
sha2 = { workspace = true }
serde_cbor = { workspace = true }
alloy = { workspace = true, default-features = false, features = ["sol-types"] }